[package]
name = "static-file-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.3"
axum-extra = "0.9.1"
clap = { version = "4.4.12", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.0", features = ["fs", "trace"] }
tracing = "0.1.40"
colored="2.1.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
